### ISSUE TITLE
파일럿 프로젝트: 1:1 문의 기능 추가

### ISSUE THREAD

**Issue by jungnoh** [jungnoh/rest-base#1]
둘이 각자 브랜치 파서 만드세요

# 작업방법
- 아래 필요 endpoint에 대한 서비스, 컨트롤러, 라우트를 각 파일에 작성
- 동일한 기능이 '간단알바' 레포에 구현되어 있으니 참고해서 작성

# 필요 endpoint
- POST /ask/write
1:1 문의를 작성 (이미 구현되어 있음)
- GET /ask/:id
문의 id에 따라 문의 내용을 가져온다. 이때, 질문 작성자 또는 관리자만 권한이 있고, 권한이 없는 경우는 404를 반환한다.
- PUT /ask/reply/:id
문의에 대한 답변을 작성한다. 관리자만 답변을 작성할 수 있다. (body 내용은 /ask/write 참조)
- GET /ask/list
내 문의 목록을 가져온다. 항목별로 제목(title), 답변여부(responded), 작성시간(createdAt)만 가져온다.
쿼리에 page를 입력받아 페이지별 목록을 가져올 수 있어야 한다. (페이지 기본값은 1)

**Comment by junhyeog** [comment]
기능 구현해서 pr 날렸습니다. #2
